//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan_36
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterRole
    {
        public int Id { get; set; }
        public string MasterId { get; set; }
        public string RoleId { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Master Master { get; set; }
    }
}
