//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan_34
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Web_DenLedEntities : DbContext
    {
        public Web_DenLedEntities()
            : base("name=Web_DenLedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblCategory> tblCategories { get; set; }
        public DbSet<tblCategoryProduct> tblCategoryProducts { get; set; }
        public DbSet<tblContact> tblContacts { get; set; }
        public DbSet<tblCustomer> tblCustomers { get; set; }
        public DbSet<tblManufacture> tblManufactures { get; set; }
        public DbSet<tblOrderDetail> tblOrderDetails { get; set; }
        public DbSet<tblOrder> tblOrders { get; set; }
        public DbSet<tblProduct_Images> tblProduct_Images { get; set; }
        public DbSet<tblProduct> tblProducts { get; set; }
        public DbSet<tblRole> tblRoles { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
    
        public virtual int tblCategory_Insert(string metaTitle, string name, Nullable<int> levels, Nullable<int> parentID, string sEOTitle, Nullable<int> typeID)
        {
            var metaTitleParameter = metaTitle != null ?
                new ObjectParameter("MetaTitle", metaTitle) :
                new ObjectParameter("MetaTitle", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var levelsParameter = levels.HasValue ?
                new ObjectParameter("Levels", levels) :
                new ObjectParameter("Levels", typeof(int));
    
            var parentIDParameter = parentID.HasValue ?
                new ObjectParameter("ParentID", parentID) :
                new ObjectParameter("ParentID", typeof(int));
    
            var sEOTitleParameter = sEOTitle != null ?
                new ObjectParameter("SEOTitle", sEOTitle) :
                new ObjectParameter("SEOTitle", typeof(string));
    
            var typeIDParameter = typeID.HasValue ?
                new ObjectParameter("TypeID", typeID) :
                new ObjectParameter("TypeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("tblCategory_Insert", metaTitleParameter, nameParameter, levelsParameter, parentIDParameter, sEOTitleParameter, typeIDParameter);
        }
    }
}
