//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan_35
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Web_DenLedEntities : DbContext
    {
        public Web_DenLedEntities()
            : base("name=Web_DenLedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblCategory> tblCategories { get; set; }
        public DbSet<tblCategoryProduct> tblCategoryProducts { get; set; }
        public DbSet<tblContact> tblContacts { get; set; }
        public DbSet<tblCustomer> tblCustomers { get; set; }
        public DbSet<tblManufacture> tblManufactures { get; set; }
        public DbSet<tblOrderDetail> tblOrderDetails { get; set; }
        public DbSet<tblOrder> tblOrders { get; set; }
        public DbSet<tblProduct_Images> tblProduct_Images { get; set; }
        public DbSet<tblProduct> tblProducts { get; set; }
        public DbSet<tblRole> tblRoles { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
    
        public virtual ObjectResult<tblCategory_List_Result> tblCategory_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tblCategory_List_Result>("tblCategory_List");
        }
    
        public virtual ObjectResult<tblProducts_List_Result> tblProducts_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tblProducts_List_Result>("tblProducts_List");
        }
    }
}
