//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan_35
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRole
    {
        public int RoleID { get; set; }
        public string NameRole { get; set; }
    }
}
